name: exercise
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: meflyup <email@example.com>
dependencies:
  browser: any
  messenger: "^0.0.7"
  polymer: ">=0.15.1 <0.17.0"
dev_dependencies:
  unittest: any
